### ISSUE TITLE
don't install symfony/event-dispatcher v3.1.4

### ISSUE THREAD

**Issue by gp187** [zf-fr/zfr-shopify#22] opened 2016-09-27 13:35 UTC
Laravel 5.3, Guzzle latest and I get this error when trying to install the plugin. 
It requires `- Can only install one of: symfony/event-dispatcher[v2.8.0, v3.1.4].`

Either version installed, I get the same error 

After downgrading some other packages as well, I also get this:
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

Pretty important error

**Comment by bakura10** [comment] 2016-09-27 14:59
Yeah, unfortunately the issue is that Guzzle Services has not yet been updated to Guzzle 6 (there is a PR running : https://github.com/guzzle/guzzle-services/pull/109) so unfortunately I'm forced to still based this library on Guzzle 3. I'm impatiently waiting!

**Comment by danizord** [comment] 2017-02-20 19:12
Fixed by https://github.com/zf-fr/zfr-shopify/pull/25

**Closed** 2017-02-20 20:04 UTC
